// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xenesjapguywwcarzjco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbmVzamFwZ3V5d3djYXJ6amNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDY0NzQsImV4cCI6MjA2MTE4MjQ3NH0.SE4rq0SzyXzcalk8bfDM0b-rDx3D8oJUf_fcuv3WflI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);